### PR TITLE
feat: add icons page

### PR DESCRIPTION
**Pull request by ddtamn**

### CODE REVIEW

**Comment by shyakadavis** [comment]
Hello, @ddtamn 

Thank you for the P.R.

In spirit of mirroring the [original](https://vercel.com/geist/icons), I was wondering if we could add more features, like the context menu, icon names...

If you are busy at the moment, then with your permission, I could help by committing directly to this P.R.

Thanks again.

**Comment by ddtamn** [comment]
Hello, @shyakadavis 

Thank you for your feedback.

I completely agree with your suggestion to add more features, such as the context menu and icon names. I am currently a bit busy, but I will try to make some commits when I have free time. However, you are welcome to commit directly to this P.R. if needed.

Thanks again!

**Comment by shyakadavis** [comment]
Hmm... the preview deployment is wrong. I'll keep investigating why it's not deploying the current branch with its changes.

**Comment by shyakadavis** [comment]
Could be related: https://github.com/huntabyte/shadcn-svelte/issues/1204 in that I'm using their workflows in order to get forked-repo previews.

**Comment by shyakadavis** [comment]
The correct deployment previews are now live. I wanted to add the search feature before merging, but IMO, good to go for now.

**Pull request merged**
