### PR TITLE
component: Snippet

### PR DESCRIPTION
**Pull request by ieedan**
Had to build one of these for work and it's not too much effort to port over so here it is.

## Notes
- Had to change all the colors to support `bg-opacity-*` (otherwise this would be much less fun with the variants)
- Currently the `dark` attribute is not implemented because I am not sure exactly how we want it to interact with variants. My best guess on the behavior is that it will just always apply the white styling shown. **Please Advise**

## API Differences
- Using `variant` instead of `type` because it is more 'shadcn' but we could change this easily to type
- They use a `width` prop which just seems unnecessary if you are giving the consumer the class prop
- `onCopy` is `on_copy` to fit the style of this project
- Using `npm create svelte` instead of `npm init next-app` because ew react
- Coloring might now be *exactly* the same because of laziness

Let me know if theres anything that needs to change!

### CODE REVIEW

**Comment by shyakadavis** [comment]
Hello, @ieedan 

Apologies for taking long to get to this. Was caught up for a while.

I'll promptly review. Just wanted to chime in and say thank you.

**Review by shyakadavis — APPROVED** [review]
Grateful for the P.R, @ieedan 🫡

**Comment by ieedan** [comment]
Thanks!

**Comment by ieedan** [comment]
One thing I am noticing is by using the `[before-content](before:content-['$'])` the copy behavior is a little weird if you aren't using the button. Most of the time users will use the button but if you try and manually highlight you can end up copying like this: 

image

The resulting copy and paste would look like this: `	pnpm create svelte@latest`

There's probably a compromise that could be found but just thought I would bring it up.

**Comment by shyakadavis** [comment]
Ah, got it. Thanks.

Will look into it; in the meantime, wanted to not resort to JS if we don't have to. 🤷

**Pull request merged**
